#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/your_database_name  # URL ??? ??????????? ? PostgreSQL
#    username: your_username                                  # ??? ???????????? ??
#    password: your_password                                  # ?????? ???????????? ??
#    driver-class-name: org.postgresql.Driver                # ??????? PostgreSQL
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect  # ??????? ??? PostgreSQL
#    hibernate:
#      ddl-auto: update                                       # ????????? ?????????? ????? ??
#    show-sql: true                                           # ?????????? SQL-??????? ? ?????
#    properties:
#      hibernate:
#        format_sql: true
vk:
  token: ${TOKEN}
  secretKey: ${SECRET_KEY}
  confirmationCode: ${CONFIRMATION_CODE}
  groupId: ${GROUP_ID}
  vocabularyPath: ${VOCABULARY_PATH}
  adminId: ${ADMIN_ID}
api:
  weather: ${WEATHER_API_TOKEN}
